export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const ADD_FAVORITE_MOVIE = 'ADD_FAVORITE_MOVIE';
export const REMOVE_FAVORITE_MOVIE = 'REMOVE_FAVORITE_MOVIE';